### PR TITLE
Update sensor_def_qcomdev.conf

### PR DESCRIPTION
**Pull request by xavinux**
Update mag x/y/z values.

### CODE REVIEW

**Comment by jerpelea** [comment]
Where have you got those values and on which device have you tested them?
Please add a comment to this commit and sign it

**Comment by xavinux** [comment]
Sorry, but didn´t have the chance to test them at the moment. Think that could be a typo error on the numeric values.

**Comment by alviteri** [comment]
sensors conf was picked from stock and until to latest release by sony it doesn't change... why are you changing those values?

**Comment by xavinux** [comment]
Think it was a typo error, and change them to a logic order.

900 -1 0x00010001
901  2  0x00010001
902 -3 0x00010001

**Comment by alviteri** [comment]
check again ...... those values are coming from suzuran not from sumire

maybe @jerpelea can explain us :)

https://github.com/sonyxperiadev/device-sony-suzuran/blob/master/rootdir/system/etc/sensors/sensor_def_qcomdev.conf#L86

**Comment by xavinux** [comment]
@ alviteri thank you very much for your information.

**Comment by xavinux** [comment]
@alviteri thank you very much for your information.

**Comment by alviteri** [comment]
either for info look as accelerometer values are not the same 

https://github.com/sonyxperiadev/device-sony-suzuran/blob/master/rootdir/system/etc/sensors/sensor_def_qcomdev.conf#L78

**Comment by xavinux** [comment]
@alviteri thank you very much for your information. Yes there they are:

900 1 0x00010001 #mag-x-axis
901 -2 0x00010001 #mag-y-axis
902 -3 0x00010001 #mag-z-axis

**Comment by alviteri** [comment]
are you having issues with that configuration? if yes can you show any log or which changes did you see putting the new values?

**Comment by xavinux** [comment]
No Sir, sorry but I didn't have the chance to test this at the moment.

**Comment by xavinux** [comment]
@alviteri no Sir, sorry but I'm not able to test this at the moment.

**Comment by xavinux** [comment]
@alviteri @jerpelea these are the differences between both targets devices parameters:

Sumire parameters values:
########################################################################
###        8994 Chipsets
########################################################################
:hardware 8994
:platform
:property
# Orientation of sensors
# accel x/y/z
700  -1 0x00010001 #accel-x-axis
701   2 0x00010001 #accel-y-axis
702  -3 0x00010001 #accel-z-axis
# gyro x/y/z
800  -1 0x00010001 #gyro-x-axis
801   2 0x00010001 #gyro-y-axis
802  -3 0x00010001 #gyro-z-axis
# mag x/y/z
900  -1 0x00010001 #mag-x-axis
901   2 0x00010001 #mag-y-axis
902  -3 0x00010001 #mag-z-axis

Suzuran parameters values:
########################################################################
###        8994 Chipsets
########################################################################
:hardware 8994
:platform
:property
# Orientation of sensors
# accel x/y/z
700   1 0x00010001 #accel-x-axis
701  -2 0x00010001 #accel-y-axis
702  -3 0x00010001 #accel-z-axis
# gyro x/y/z
800   1 0x00010001 #gyro-x-axis
801  -2 0x00010001 #gyro-y-axis
802  -3 0x00010001 #gyro-z-axis
# mag x/y/z
900   1 0x00010001 #mag-x-axis
901  -2 0x00010001 #mag-y-axis
902  -3 0x00010001 #mag-z-axis

**Comment by xavinux** [comment]
@alviteri @jerpelea these are the differences between both targets devices parameters:

sumire
########################################################################

### 8994 Chipsets

########################################################################
:hardware 8994
:platform
:property

# Orientation of sensors

# accel x/y/z

700  -1 0x00010001 #accel-x-axis
701   2 0x00010001 #accel-y-axis
702  -3 0x00010001 #accel-z-axis

# gyro x/y/z

800  -1 0x00010001 #gyro-x-axis
801   2 0x00010001 #gyro-y-axis
802  -3 0x00010001 #gyro-z-axis

# mag x/y/z

900  -2 0x00010001 #mag-x-axis
901   3 0x00010001 #mag-y-axis
902  -1 0x00010001 #mag-z-axis

suzuran
########################################################################

### 8994 Chipsets

########################################################################
:hardware 8994
:platform
:property

# Orientation of sensors

# accel x/y/z

700   1 0x00010001 #accel-x-axis
701  -2 0x00010001 #accel-y-axis
702  -3 0x00010001 #accel-z-axis

# gyro x/y/z

800   1 0x00010001 #gyro-x-axis
801  -2 0x00010001 #gyro-y-axis
802  -3 0x00010001 #gyro-z-axis

# mag x/y/z

900   1 0x00010001 #mag-x-axis
901  -2 0x00010001 #mag-y-axis
902  -3 0x00010001 #mag-z-axis

In suzuran accel, gyro and mag have the same values, but in sumire only accel and giro have the same parameters values.

**Pull request closed without merging**
